"""Diagnostic: Davison image-series derivation for sphere with white BC.

Created by numerics-investigator on 2026-04-24.
Issue #132 viability probe — Davison method-of-images path.

Investigation goal
==================
Test the hypothesis that the spherical Peierls equation with the
Davison ``u = rφ`` substitution reduces to a 1-D-slab-like problem on
``(0, R)`` with kernel ``E_1`` plus an INFINITE image series:

- vacuum-at-center image at ``-r'`` (automatic from the Davison
  substitution, sign ``-``) — this is the well-known KNOWN form.
- additional images required by the OUTER BC.

Mathematical structure
======================
Start from the spherical Peierls equation for the SCALAR flux φ(r):

.. math::

   φ(r) = \\frac{c}{4πr} \\int_0^R \\frac{r'}{|r-r'|} \\cdot
          [E_1(τ|r-r'|) - E_1(τ|r+r'|)] \\cdot Σ_t \\, φ(r') \\, r' \\, dr'

(Davison 1958 §11.6, "The angular density of neutrons in a finite
medium"; written for fission with ``c = ν_f Σ_f / Σ_t``).

Multiplying by ``r``: u(r) = r φ(r):

.. math::

   u(r) = \\frac{c Σ_t}{2} \\int_0^R [E_1(τ|r-r'|) - E_1(τ(r+r'))]
          u(r') \\, dr'

(after absorbing the ``r/r`` factor and recognising
``r' u(r') = r' · r' φ(r') = r'^2 φ(r')`` which then cancels with the
``1/r`` outer factor multiplied by ``r`` — careful algebra below).

The (r+r') term enforces ``u(0) = 0`` automatically — the "image at
``-r'``" interpretation. This is the **vacuum-at-center virtual image**,
NOT a physical BC. It exists in every spherical formulation regardless
of the outer BC.

For the OUTER surface r=R:

- **Vacuum BC** (φ = 0 at infinity, no return): no extra image series
  needed. The integral is just over (0, R).
- **Specular reflection** (perfect mirror): infinite image series of
  alternating signs at positions
  ``±r', ±(2R±r'), ±(4R±r'), ...``
  generated by alternately reflecting across r=0 (sign flip from the
  Davison substitution u(0)=0) and across r=R (sign flip from the
  specular-mirror condition).
- **White BC** (Mark, isotropic re-emission of returning current): the
  re-emission is NOT a per-ray reflection. Method of images does NOT
  apply directly to white BC.

This script DERIVES the specular-reflection image series (since white
BC does not admit one) and reports the structure for downstream
testing in Step 2 (numerical convergence).

Key takeaway
============
If the cp_sphere k_inf reference (= 0.6480 for 1G/2R) corresponds to
the **white-BC Mark closure**, then a method-of-images derivation will
NOT recover it — image method gives the SPECULAR-reflection k_eff,
which is a different number unless the angular flux on the surface
happens to be isotropic (which it is only for fully homogeneous
cases). For 1G/1R (homogeneous), specular and white BC give the same
k_eff = k_inf = 1.5 trivially. The test of viability is whether the
specular-image k_eff matches cp_sphere on 1G/2R (heterogeneous).

NOTE — this is not a pytest assertion test; it is a derivation +
print script. Promote the convergence test (Step 2) to pytest if it
gives a meaningful answer.
"""

from __future__ import annotations

import sympy as sp


def derive_image_positions_and_signs(n_images: int = 10) -> None:
    """Enumerate image positions and signs for sphere of radius R,
    source at r', specular reflection at r=R, vacuum sign-flip at r=0.

    Algorithm: start with the source at +r' (sign +1). Apply the two
    reflection operators alternately:
      - R_0 (vacuum at r=0): r → -r, sign flip
      - R_R (specular at r=R): r → 2R-r, sign flip

    The full image set is generated by all words in {R_0, R_R}*. By
    composition: R_R · R_0 = (r → 2R+r), no net sign flip; R_0 · R_R
    = (r → r-2R), no net sign flip. So composing both gives a
    translation by 2R; alternating gives sign flips.

    The image positions form a 2R-periodic structure.
    """
    R, rp = sp.symbols("R r'", positive=True)

    print("=" * 76)
    print("Image positions and signs for sphere with vacuum-center +")
    print("specular-mirror at r=R")
    print("=" * 76)
    print()
    print(f"  Source position: r'  with sign +1")
    print()
    print(f"  Reflection operators:")
    print(f"    R_0 (vacuum at r=0, from Davison u(0)=0): r → -r, sign × (-1)")
    print(f"    R_R (specular at r=R):                    r → 2R-r, sign × (-1)")
    print()
    print(f"  First {n_images} images by breadth-first generation:")
    print(f"  {'word':>20} {'position':>20} {'sign':>6}")

    # BFS over reflection words
    seen = {(rp, +1)}
    queue = [(rp, +1, "")]
    images = [(rp, +1, "")]

    while queue and len(images) < n_images:
        pos, sign, word = queue.pop(0)
        # Apply R_0
        new_pos_0 = sp.simplify(-pos)
        new_sign_0 = -sign
        if (new_pos_0, new_sign_0) not in seen:
            seen.add((new_pos_0, new_sign_0))
            queue.append((new_pos_0, new_sign_0, word + "0"))
            images.append((new_pos_0, new_sign_0, word + "0"))
        # Apply R_R
        new_pos_R = sp.simplify(2 * R - pos)
        new_sign_R = -sign
        if (new_pos_R, new_sign_R) not in seen:
            seen.add((new_pos_R, new_sign_R))
            queue.append((new_pos_R, new_sign_R, word + "R"))
            images.append((new_pos_R, new_sign_R, word + "R"))

    for pos, sign, word in images[:n_images]:
        word_disp = word if word else "(identity)"
        print(f"  {word_disp:>20} {str(pos):>20} {sign:>+6d}")

    print()
    print("  Pattern: 2R-periodic structure with alternating signs.")
    print("  Image positions = {± r' + 2nR : n ∈ Z} = {2nR + r', 2nR - r' : n ∈ Z}")
    print("  Sign of (2nR + r') is (-1)^|n|, sign of (2nR - r') is (-1)^|n+1|")
    print("  The kernel becomes:")
    print()
    print("    K_specular(r, r') = sum_{n=-inf}^{inf} (-1)^|n| ·")
    print("                          [E_1(τ|r - (2nR+r')|) - E_1(τ|r - (2nR-r')|)]")
    print()
    print("  Truncating at |n| ≤ N_max gives 2(2N_max+1) image terms.")


def verify_n0_term_is_vacuum_kernel() -> None:
    """Confirm that the n=0 term of the image series reduces to the
    Davison vacuum kernel:

        K_vacuum(r, r') = E_1(τ|r-r'|) - E_1(τ(r+r'))

    where the +r' image (Davison center reflection) gives the (r+r')
    sign-flip term.
    """
    print()
    print("=" * 76)
    print("Sanity gate: n=0 term must match Davison vacuum kernel")
    print("=" * 76)
    print()
    print("  At n=0, image positions are {r', -r'} with signs {+1, -1}")
    print("  K_n=0(r, r') = E_1(τ|r-r'|) - E_1(τ|r-(-r')|)")
    print("             = E_1(τ|r-r'|) - E_1(τ(r+r'))   [since r,r'>0]")
    print()
    print("  Matches Davison 1958 §11.6 vacuum kernel.   PASS")


def verify_white_bc_does_not_admit_image_series() -> None:
    """Explain why white BC (Mark, isotropic re-emission) does NOT
    admit a per-ray image series."""
    print()
    print("=" * 76)
    print("CRITICAL CAVEAT: white BC and method-of-images")
    print("=" * 76)
    print()
    print("  Method of images works for boundary conditions that act")
    print("  POINTWISE on the angular flux:")
    print("    - vacuum: ψ(r_b, Ω·n<0) = 0")
    print("    - specular: ψ(r_b, Ω·n<0) = ψ(r_b, Ω·n>0) with Ω → Ω - 2(Ω·n)n")
    print()
    print("  White BC (Mark) acts NON-POINTWISE on the angular flux:")
    print("    ψ⁻(r_b, Ω) = J⁺(r_b)/π = (1/π) ∫_{Ω·n>0} (Ω'·n) ψ(r_b, Ω') dΩ'")
    print()
    print("  The re-emitted angular flux is the AVERAGE of the outgoing")
    print("  current — it does NOT depend on the per-ray angle Ω. This")
    print("  cannot be reproduced by mirror images of the source: each")
    print("  image source still emits with its own angular distribution,")
    print("  which is not isotropic at the outer surface.")
    print()
    print("  CONSEQUENCE: the Davison image method, applied to the")
    print("  spherical Peierls equation with white BC, would produce")
    print("  the SPECULAR-reflection k_eff, NOT the white-BC k_eff.")
    print()
    print("  These two coincide ONLY when the outgoing angular flux")
    print("  at r=R is isotropic — i.e., for a fully homogeneous cell")
    print("  (1G/1R) or in the asymptotic optically-thick limit.")
    print()
    print("  For heterogeneous cases (1G/2R fuel-mod), specular ≠ white")
    print("  in general. The image method CANNOT bypass the Mark closure")
    print("  for the heterogeneous case — it solves a different problem.")


if __name__ == "__main__":
    derive_image_positions_and_signs(n_images=10)
    verify_n0_term_is_vacuum_kernel()
    verify_white_bc_does_not_admit_image_series()
