"""Generate the Peierls capability-matrix include file.

Emits ``docs/theory/_peierls_capability_matrix.inc.rst``, an RST
fragment ``.. include::``'d by ``docs/theory/peierls_unified.rst``
at :ref:`theory-peierls-capabilities`.

The data is the **single source of truth** for which continuous
Peierls references are shipped: it is pulled from
:func:`orpheus.derivations.peierls_cases.capability_rows`, the same
registry function that :func:`orpheus.derivations.peierls_cases.continuous_cases`
iterates (see the "Metadata-only enumeration" section of that
module). Running this tool therefore cannot drift from the shipping
registry — any new reference added to ``_class_{a,b}_cases()`` must
also appear in ``capability_rows()`` or the assertion in the matrix
cross-check test (see
``tests/derivations/test_peierls_capability_matrix.py`` when it
lands) will fail.

This replaces the hand-maintained ``.. list-table::`` that used to
live inline in ``peierls_unified.rst``. The include file is
regenerated by ``docs/conf.py`` on every Sphinx build via
:func:`_regenerate_peierls_matrix`.

Usage::

    python -m tools.verification.generate_peierls_matrix [OUT_RST]

``OUT_RST`` defaults to ``docs/theory/_peierls_capability_matrix.inc.rst``.

See also
--------
:mod:`tools.verification.generate_matrix`
    Sibling tool that generates ``docs/verification/matrix.rst``
    from the pytest registry. Both tools share the
    ``setup(app) -> app.connect("builder-inited", ...)`` hook
    pattern in ``docs/conf.py``.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT = REPO_ROOT / "docs" / "theory" / "_peierls_capability_matrix.inc.rst"


_GEOM_LABELS = {
    "slab": "slab",
    "cylinder-1d": "cylinder-1d",
    "sphere-1d": "sphere-1d",
}


def _fmt_r0(r0: float | None) -> str:
    """Render the ``r_0/R`` column cell.

    Slab (``r0 is None``) has no cavity concept — emit an em-dash.
    Curvilinear hollow cases show the raw ratio at 1-decimal precision.
    """
    if r0 is None:
        return "—"
    return f"{r0:.1f}"


def _list_table(
    title: str,
    headers: list[str],
    widths: list[int],
    rows: list[list[str]],
) -> str:
    """Render a ``.. list-table::`` block.

    Using the list-table form (not csv-table) because several cells
    contain LaTeX ``:math:`` directives and commas that would confuse
    csv parsing (same pitfall as feedback_peierls_docs.md).
    """
    if len(headers) != len(widths):
        raise ValueError(
            f"header/width count mismatch: "
            f"{len(headers)} headers vs {len(widths)} widths"
        )
    lines: list[str] = []
    lines.append(f".. list-table:: {title}")
    lines.append("   :header-rows: 1")
    lines.append(f"   :widths: {' '.join(str(w) for w in widths)}")
    lines.append("")
    # Header row
    lines.append(f"   * - {headers[0]}")
    for h in headers[1:]:
        lines.append(f"     - {h}")
    # Data rows
    for row in rows:
        if len(row) != len(headers):
            raise ValueError(
                f"row/header count mismatch: row={row!r}, "
                f"headers={headers!r}"
            )
        lines.append(f"   * - {row[0]}")
        for cell in row[1:]:
            lines.append(f"     - {cell}")
    lines.append("")
    return "\n".join(lines)


def _render(rows: list[dict]) -> str:
    """Render the full include file from the metadata rows.

    Layout mirrors the pre-generator hand-written matrix:

    1. Intro note pinning the source to ``capability_rows()``.
    2. Main shipped-references table (all rows together).

    Class A / B split tables live *outside* this include file — they
    document the closure matrix per shape rather than the shipped
    references per row, and are stable (change rarely), so keeping
    them hand-written in ``peierls_unified.rst`` is the lower-churn
    choice. If that assumption breaks (e.g. Issue #103 ships the
    first Class B reference), revisit this split.
    """
    lines: list[str] = []
    lines.append(
        "..\n"
        "   AUTO-GENERATED by "
        "``tools/verification/generate_peierls_matrix.py``.\n"
        "   Do not edit by hand — changes will be overwritten on the\n"
        "   next Sphinx build. The single source of truth is\n"
        "   ``orpheus.derivations.peierls_cases.capability_rows()``.\n"
    )
    lines.append("")

    # Main table — every shipped continuous reference.
    headers = [
        "Reference name",
        "Geometry",
        "n_g",
        "n_reg",
        r":math:`r_0 / R`",
        "Closure",
        "Accuracy class",
    ]
    widths = [33, 12, 8, 8, 12, 15, 12]

    data_rows = []
    for r in rows:
        data_rows.append([
            f"``{r['name']}``",
            _GEOM_LABELS.get(str(r["geometry"]), str(r["geometry"])),
            str(r["n_groups"]),
            str(r["n_regions"]),
            _fmt_r0(r["r0_over_R"]),  # type: ignore[arg-type]
            str(r["closure"]),
            str(r["accuracy"]),
        ])

    lines.append(
        _list_table(
            title=(
                "Shipped Peierls continuous references "
                "(operator_form ``integral-peierls``)"
            ),
            headers=headers,
            widths=widths,
            rows=data_rows,
        )
    )

    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    argv = argv if argv is not None else sys.argv[1:]
    out_path = Path(argv[0]) if argv else DEFAULT_OUT
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # Importing peierls_cases is cheap — capability_rows() does not
    # invoke any eigenvalue solver (that would bottleneck Sphinx
    # builds to O(minutes)). The registry-aligned cross-check lives
    # in the test suite, not here.
    from orpheus.derivations.peierls_cases import capability_rows

    rows = capability_rows()
    rst = _render(rows)
    out_path.write_text(rst, encoding="utf-8")
    print(
        f"wrote {out_path.relative_to(REPO_ROOT)} "
        f"({len(rows)} Peierls capability rows)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
